# Generated by Django 3.2.20 on 2023-08-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingrediant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediant',
            new_name='Ingredient',
        ),
    ]
